In [2]:
import pandas as pd
from process_results import process_results_folder_json
from training_logs_analysis import parse_client_csv, process_fp_logs

In [3]:
gat_cora_csv = "/home/brian_bosho/FP/FP/federated-gnn/src/results/GAT_final/planetoid_300_rounds_pe/Cora_diffusion_GAT_beta10000_clients10/training_Cora_diffusion_GAT_beta10000_clients10_20250605_194510.csv"

gat_cora_logs = parse_client_csv(gat_cora_csv)

In [4]:
acc_df = gat_cora_logs['acc_df']
acc_df.head()

client_id           0       1         2    3         4         5         6  \
round epoch
0     0      0.000000  0.0000  0.066667  0.2  0.214286  0.133333  0.133333
      1      0.357143  0.3125  0.333333  0.6  0.357143  0.266667  0.400000
      2      0.357143  0.3125  0.266667  0.6  0.357143  0.266667  0.400000
1     0      0.285714  0.1875  0.400000  0.4  0.357143  0.200000  0.400000
      1      0.357143  0.3125  0.333333  0.6  0.357143  0.266667  0.400000

client_id           7         8         9
round epoch
0     0      0.071429  0.142857  0.230769
      1      0.214286  0.285714  0.461538
      2      0.428571  0.428571  0.461538
1     0      0.428571  0.214286  0.384615
      1      0.428571  0.357143  0.384615

In [8]:
acc_df_step = gat_cora_logs['acc_df_step']

acc_df_step.head(20)

client_id,0,1,2,3,4,5,6,7,8,9
step,,,,,,,,,,
0,0.000000,0.0000,0.066667,0.2,0.214286,0.133333,0.133333,0.071429,0.142857,0.230769
1,0.357143,0.3125,0.333333,0.6,0.357143,0.266667,0.400000,0.214286,0.285714,0.461538
2,0.357143,0.3125,0.266667,0.6,0.357143,0.266667,0.400000,0.428571,0.428571,0.461538
3,0.285714,0.1875,0.400000,0.4,0.357143,0.200000,0.400000,0.428571,0.214286,0.384615
4,0.357143,0.3125,0.333333,0.6,0.357143,0.266667,0.400000,0.428571,0.357143,0.384615
5,0.357143,0.3125,0.266667,0.6,0.357143,0.266667,0.466667,0.428571,0.428571,0.461538
6,0.500000,0.4375,0.666667,0.6,0.500000,0.333333,0.533333,0.500000,0.500000,0.538462
7,0.357143,0.3125,0.466667,0.6,0.357143,0.266667,0.400000,0.428571,0.428571,0.461538
8,0.357143,0.3125,0.400000,0.6,0.357143,0.266667,0.466667,0.428571,0.428571,0.461538
9,0.571429,0.5625,0.933333,0.9,0.500000,0.466667,0.600000,0.571429,0.714286,0.615385
10,0.357143,0.3125,0.600000,0.6,0.357143,0.333333,0.466667,0.500000,0.428571,0.461538
11,0.357143,0.3125,0.400000,0.6,0.357143,0.333333,0.466667,0.428571,0.428571,0.461538
12,0.857143,0.8125,1.000000,1.0,0.714286,0.666667,0.666667,0.642857,0.857143,0.692308
13,0.357143,0.3125,0.600000,0.6,0.357143,0.333333,0.466667,0.571429,0.571429,0.461538
14,0.357143,0.3125,0.533333,0.6,0.357143,0.333333,0.533333,0.500000,0.571429,0.461538
15,0.857143,0.8125,1.000000,1.0,0.785714,0.800000,0.800000,0.714286,0.928571,0.692308
16,0.357143,0.3125,0.733333,0.6,0.357143,0.400000,0.466667,0.642857,0.571429,0.538462
17,0.357143,0.3125,0.733333,0.6,0.357143,0.333333,0.533333,0.642857,0.571429,0.461538
18,0.857143,0.8125,1.000000,1.0,1.000000,0.800000,0.800000,0.785714,0.928571,0.692308
19,0.357143,0.3125,0.733333,0.6,0.357143,0.400000,0.466667,0.642857,0.571429,0.538462

In [11]:
final_acc_df = gat_cora_logs['final_acc_df']
final_acc_df.head(50)

client_id,0,1,2,3,4,5,6,7,8,9
round,,,,,,,,,,
0,0.357143,0.3125,0.266667,0.6,0.357143,0.266667,0.400000,0.428571,0.428571,0.461538
1,0.357143,0.3125,0.266667,0.6,0.357143,0.266667,0.466667,0.428571,0.428571,0.461538
2,0.357143,0.3125,0.400000,0.6,0.357143,0.266667,0.466667,0.428571,0.428571,0.461538
3,0.357143,0.3125,0.400000,0.6,0.357143,0.333333,0.466667,0.428571,0.428571,0.461538
4,0.357143,0.3125,0.533333,0.6,0.357143,0.333333,0.533333,0.500000,0.571429,0.461538
5,0.357143,0.3125,0.733333,0.6,0.357143,0.333333,0.533333,0.642857,0.571429,0.461538
6,0.357143,0.3125,0.733333,0.6,0.357143,0.400000,0.533333,0.642857,0.571429,0.461538
7,0.357143,0.3750,0.800000,0.6,0.357143,0.466667,0.533333,0.714286,0.642857,0.461538
8,0.357143,0.3750,0.800000,0.6,0.357143,0.466667,0.533333,0.785714,0.642857,0.615385
9,0.357143,0.5000,0.800000,0.6,0.357143,0.533333,0.533333,0.785714,0.714286,0.615385
10,0.428571,0.5625,0.800000,0.6,0.357143,0.600000,0.600000,0.785714,0.714286,0.692308
11,0.642857,0.5625,0.800000,0.7,0.357143,0.666667,0.600000,0.785714,0.714286,0.692308
12,0.642857,0.5625,0.866667,0.7,0.357143,0.800000,0.666667,0.785714,0.785714,0.692308
13,0.714286,0.6875,0.933333,0.7,0.500000,0.800000,0.666667,0.785714,0.785714,0.692308
14,0.714286,0.7500,0.933333,0.7,0.571429,0.800000,0.666667,0.785714,0.785714,0.923077
15,0.785714,0.8125,0.933333,0.8,0.857143,0.866667,0.666667,0.785714,0.857143,0.923077
16,0.785714,0.9375,0.933333,0.9,0.857143,0.933333,0.733333,0.785714,0.857143,0.923077
17,0.785714,0.9375,1.000000,0.9,0.928571,0.933333,0.733333,0.857143,0.857143,0.923077
18,0.857143,1.0000,1.000000,1.0,0.928571,0.933333,0.866667,0.857143,0.857143,0.923077
19,0.857143,1.0000,1.000000,1.0,1.000000,1.000000,0.866667,0.857143,0.928571,0.923077
20,0.857143,1.0000,1.000000,1.0,1.000000,1.000000,0.933333,0.857143,0.928571,0.923077
21,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,0.857143,0.928571,0.923077
22,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,0.857143,0.928571,0.923077
23,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,0.928571,1.000000,0.923077
24,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,0.923077
25,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
26,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
27,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
28,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
29,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
30,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
31,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
32,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
33,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
34,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
35,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
36,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
37,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
38,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
39,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
40,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
41,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
42,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
43,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
44,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
45,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
46,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
47,0.928571,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
48,1.000000,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
49,1.000000,1.0000,1.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000